name: test_suite_tool
resolution: workspace
description: A tool and mixin for managing test suites, including README generation and suite directory handling.
version: 0.2.0
environment:
  sdk: ^3.11.0

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0