name: domain_usecases
resolution: workspace
description: Domain usecases for Resume Suckage clean architecture
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  domain_entities:
    path: ../domain_entities
  domain_contracts:
    path: ../domain_contracts
  fpdart: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
  mocktail: ^1.0.4