name: resumesux_domain
description: The cleanarch domain and data layers for Resume Suckage
version: 1.1.2
license: Apache-2.0
# repository: https://github.com/my_org/my_repo
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.11.0

dependencies:
  melos: ^7.4.0
  uuid: ^4.4.2
  fpdart: ^1.2.0
  http: ^1.2.2
  intl: ^0.20.2
  yaml: ^3.1.2
  json_schema: ^5.2.0
  path: ^1.9.1
  markdown: ^7.2.2
  equatable: ^2.0.7
  id_logging: ^1.2.0

workspace:
  - packages/*

dev_dependencies:
  lints: ^6.0.0
  husky: ^0.1.7
  mocktail: ^1.0.4
  test: ^1.28.0
  resumesux_db_sembast:
    path: packages/resumesux_db_sembast
  test_suite_tool:
    path: packages/test_suite_tool
