name: resumesux_domain
description: The cleanarch domain and data layers for Resume Suckage
version: 1.1.2
license: Apache-2.0
# repository: https://github.com/my_org/my_repo
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  fpdart: ^1.2.0
  equatable: ^2.0.7
  id_pair_set: ^1.0.0
  id_registry: ^1.0.0
  http: ^1.0.0
  yaml: ^3.1.2
  intl: ^0.20.2
  path: ^1.9.1
  json_schema: ^5.2.2
  mcp_dart: ^1.2.1
  markdown: ^7.2.2
  crypto: ^3.0.7
  id_logging:
    git: https://github.com/staylorx/id_logging

dev_dependencies:
  lints: ^6.0.0
  husky: ^0.1.7
  mocktail: ^1.0.4
  test: ^1.28.0
  resumesux_db_sembast:
    path: packages/resumesux_db_sembast
