name: basic_resume_generation_example
description: A basic example of generating a resume using resumesux_domain.

environment:
  sdk: ^3.10.0

dependencies:
  resumesux_domain:
    path: ../..
  fpdart: ^1.2.0
  http: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
