name: test_readme_manager
description: A package for managing README files in test suites.
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0