name: datasource_markdown
resolution: workspace
description: Markdown datasource implementation for Resume Suckage
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  domain_entities:
    path: ../domain_entities
  domain_contracts:
    path: ../domain_contracts
  markdown: ^7.2.2
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0