name: datasource_config
resolution: workspace
description: Config datasource implementation for Resume Suckage
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  domain_entities:
    path: ../domain_entities
  domain_contracts:
    path: ../domain_contracts
  yaml: ^3.1.2
  path: ^1.9.1
  json_schema: ^5.2.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0