name: repository_adapters_sembast
resolution: workspace
description: Sembast datasource implementation for Resume Suckage
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  domain_entities:
    path: ../domain_entities
  domain_contracts:
    path: ../domain_contracts
  sembast: ^3.8.6
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0