name: dataservice_config
resolution: workspace
description: Config dataservice for Resume Suckage clean architecture
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  domain_contracts:
    path: ../domain_contracts
  datasource_config:
    path: ../datasource_config

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0