name: dataservice_sembast
resolution: workspace
description: Sembast dataservice for Resume Suckage clean architecture
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  domain_contracts:
    path: ../domain_contracts
  repository_adapters_sembast:
    path: ../repository_adapters_sembast

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0